### PR TITLE
ci/fix: Deploying websites using Custom Domain

### PR DESCRIPTION
**Pull request by ayushsoni1010**
#6 is fixed by this PR changes

### CODE REVIEW

**Comment by amitu** [comment]
@ayushsoni1010, the PR has changed related to your repo, please undo them. Also instead of instruction, write a shell script which does the right thing. Put the script in .github/ and call it from your workflow.

**Comment by ayushsoni1010** [comment]
Alright, I will work on it

**Comment by amitu** [comment]
@ayushsoni1010, @Arpita-Jaiswal, we need this soonish.

**Comment by gsalunke** [comment]
@ayushsoni1010 
For now I have added the commented one via this commit:
https://github.com/fastn-stack/fastn-template/commit/1f7d1113d9d46d5827236130a66cb8e3139551e1

When the shell-script (https://github.com/fastn-stack/fastn-template/pull/8#issuecomment-1556780866) is ready plz raise new PR.

CC: @amitu @Arpita-Jaiswal @Heulitig

**Pull request closed without merging**
